// <auto-generated />
using System;
using BudgetWise.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetWise.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Budget.domain.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000m,
                            Category = "Salary",
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Monthly salary",
                            Type = 1,
                            UserId = "demo"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 120m,
                            Category = "Food",
                            Date = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Groceries",
                            Type = 2,
                            UserId = "demo"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 60m,
                            Category = "Transport",
                            Date = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gas",
                            Type = 2,
                            UserId = "demo"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 800m,
                            Category = "Housing",
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rent",
                            Type = 2,
                            UserId = "demo"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 500m,
                            Category = "Freelance",
                            Date = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Design project",
                            Type = 1,
                            UserId = "demo"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 45m,
                            Category = "Entertainment",
                            Date = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Movie tickets",
                            Type = 2,
                            UserId = "demo"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 200m,
                            Category = "Shopping",
                            Date = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clothes",
                            Type = 2,
                            UserId = "demo"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 90m,
                            Category = "Health",
                            Date = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pharmacy",
                            Type = 2,
                            UserId = "demo"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 150m,
                            Category = "Education",
                            Date = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Online course",
                            Type = 2,
                            UserId = "demo"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 35m,
                            Category = "Food",
                            Date = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Restaurant",
                            Type = 2,
                            UserId = "demo"
                        });
                });

            modelBuilder.Entity("Budget.domain.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
