name: CI/CD with Docker

on:
  push:
    branches: [ "master" ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./BudgetWise/BudgetWise.csproj

      - name: Build
        run: dotnet build ./BudgetWise/BudgetWise.csproj --configuration Release --no-restore

      - name: Build Docker image
        run: docker build -t budget-app .
